name: Docker Deploy

on:
  push: 
    branches:
      -main


jobs:
  build:
    runs-on:  ubuntu-latest
      steps:
        -name: Checkout code
        - uses: actions/checkout@v2

        - name: setup docker buildx
        - uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
        - uses: docker/login-actions@v1
        with :
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Build and Push Docker Image
        - uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dokerfile
            push: true
            tags: username/repository:latest

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps: 
      -name: Deploy to server
      run: |
        ssh user@server "docker pull username/repository:latest && docker run -d -p 5000:5000 username/repository:latest"
