name: Model Evaluation

on:
  push:
    branches: 
      - main

jobs:
  evaluate:
    runs-on: ubuntu_latest
    steps:
      -name: Checkout code
      uses: actions/checkout@v2

      -name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:'3.8'

      
      -name: Install dependencies
      run: | 
        pip install -r requirements.txt

      -name: run model evaluation
      run: |
      python evaluation.py

